# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='crafts',
            options={'verbose_name_plural': 'Crafts'},
        ),
        migrations.AlterModelOptions(
            name='governorates',
            options={'verbose_name_plural': 'Governorates'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='specializations',
            options={'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name_plural': 'Subscribe'},
        ),
        migrations.AlterModelOptions(
            name='workshops',
            options={'verbose_name_plural': 'Workshops'},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={'verbose_name_plural': 'Zones'},
        ),
    ]
