# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170324_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshops',
            name='crafts',
        ),
        migrations.AddField(
            model_name='workshops',
            name='crafts',
            field=models.ManyToManyField(to='main.Crafts'),
        ),
    ]
