# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170326_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
